module.exports = {
  less: {
    fileExtension: 'less',
    stack: 'less',
  },
  sass: {
    fileExtension: 'sass',
    stack: 'sass',
  },
  blacklist: [
    'position',
    'display',
    'float',
    'right',
    'top',
    'left',
    'z-index',
    'cursor',
    'transition',
    'transition-property',
    'transition-duration',
    'transition-timing-function',
    'transition-delay',
    'transform',
    'transform-origin',
    'transform-style',
    'animation',
    'direction',
  ],
}
